CREATE TABLE public.book_category
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    category_type character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT book_category_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.book_category
    OWNER to admin;