version: "3"
services:
  postgreSQL:
    restart: always
    image: sameersbn/postgresql:10-2
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - DEBUG=false
      - DB_USER=admin
      - DB_PASS=admin
      - DB_NAME=praca_magisterska
  soap_vs_rest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soap_vs_rest
    depends_on:
      - postgreSQL
    ports:
      - "8080:8080"

