version: "3"
services:
  rest_vs_soap2:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    container_name: soap_vs_rest
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/praca_magisterska
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=praca_magisterska
    restart: unless-stopped
volumes:
  postgres-data: