version: "3"
services:
  PostgreSQL:
    restart: always
    image: sameersbn/postgresql:10-2
    ports:
    - "5432:5432"
    environment:
    - DEBUG=false
    - DB_USER=admin
    - DB_PASS=admin
    - DB_NAME=praca_magisterska
