//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.24 at 11:07:53 PM CET 
//


package soap;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FindBookCategoryRequest_QNAME = new QName("https://www.praca_magister/soap_vs_rest/books.com", "FindBookCategoryRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetUserResponse }
     * 
     */
    public GetUserResponse createGetUserResponse() {
        return new GetUserResponse();
    }

    /**
     * Create an instance of {@link EditUserRequest }
     * 
     */
    public EditUserRequest createEditUserRequest() {
        return new EditUserRequest();
    }

    /**
     * Create an instance of {@link TestRequestSendAndReceivResponse }
     * 
     */
    public TestRequestSendAndReceivResponse createTestRequestSendAndReceivResponse() {
        return new TestRequestSendAndReceivResponse();
    }

    /**
     * Create an instance of {@link DeleteBookRequest }
     * 
     */
    public DeleteBookRequest createDeleteBookRequest() {
        return new DeleteBookRequest();
    }

    /**
     * Create an instance of {@link TestOtherObject2 }
     * 
     */
    public TestOtherObject2 createTestOtherObject2() {
        return new TestOtherObject2();
    }

    /**
     * Create an instance of {@link AddBookRequest }
     * 
     */
    public AddBookRequest createAddBookRequest() {
        return new AddBookRequest();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link AddUserRequest }
     * 
     */
    public AddUserRequest createAddUserRequest() {
        return new AddUserRequest();
    }

    /**
     * Create an instance of {@link FindBookCategoryResponse }
     * 
     */
    public FindBookCategoryResponse createFindBookCategoryResponse() {
        return new FindBookCategoryResponse();
    }

    /**
     * Create an instance of {@link EditBookRequest }
     * 
     */
    public EditBookRequest createEditBookRequest() {
        return new EditBookRequest();
    }

    /**
     * Create an instance of {@link GetBookRequest }
     * 
     */
    public GetBookRequest createGetBookRequest() {
        return new GetBookRequest();
    }

    /**
     * Create an instance of {@link GetUserRequest }
     * 
     */
    public GetUserRequest createGetUserRequest() {
        return new GetUserRequest();
    }

    /**
     * Create an instance of {@link TestRequestSendAndReceivRequest }
     * 
     */
    public TestRequestSendAndReceivRequest createTestRequestSendAndReceivRequest() {
        return new TestRequestSendAndReceivRequest();
    }

    /**
     * Create an instance of {@link SecureRequestTest }
     * 
     */
    public SecureRequestTest createSecureRequestTest() {
        return new SecureRequestTest();
    }

    /**
     * Create an instance of {@link DeleteUserRequest }
     * 
     */
    public DeleteUserRequest createDeleteUserRequest() {
        return new DeleteUserRequest();
    }

    /**
     * Create an instance of {@link Book }
     * 
     */
    public Book createBook() {
        return new Book();
    }

    /**
     * Create an instance of {@link SecureResponseTest }
     * 
     */
    public SecureResponseTest createSecureResponseTest() {
        return new SecureResponseTest();
    }

    /**
     * Create an instance of {@link UserRoles }
     * 
     */
    public UserRoles createUserRoles() {
        return new UserRoles();
    }

    /**
     * Create an instance of {@link TestObjectMain }
     * 
     */
    public TestObjectMain createTestObjectMain() {
        return new TestObjectMain();
    }

    /**
     * Create an instance of {@link GetBookResponse }
     * 
     */
    public GetBookResponse createGetBookResponse() {
        return new GetBookResponse();
    }

    /**
     * Create an instance of {@link TestOtherObject1 }
     * 
     */
    public TestOtherObject1 createTestOtherObject1() {
        return new TestOtherObject1();
    }

    /**
     * Create an instance of {@link BookCategory }
     * 
     */
    public BookCategory createBookCategory() {
        return new BookCategory();
    }

    /**
     * Create an instance of {@link TestRequestSendOnly }
     * 
     */
    public TestRequestSendOnly createTestRequestSendOnly() {
        return new TestRequestSendOnly();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.praca_magister/soap_vs_rest/books.com", name = "FindBookCategoryRequest")
    public JAXBElement<Object> createFindBookCategoryRequest(Object value) {
        return new JAXBElement<Object>(_FindBookCategoryRequest_QNAME, Object.class, null, value);
    }

}
