//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.23 at 05:51:27 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.praca_magister/soap_vs_rest/books.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package soap;
