//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.23 at 04:27:47 PM CET 
//


package soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="field1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field6" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field7" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field8" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field9" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field10" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field11" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field12" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field13" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field14" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field15" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field16" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field17" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field18" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field19" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field20" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field21" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field22" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field23" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field24" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field25" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field26" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field27" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field28" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field29" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field30" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field31" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field32" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field33" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field34" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field35" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field36" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field37" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field38" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field39" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field40" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field41" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field42" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field43" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field44" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field45" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field46" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field47" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field48" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field49" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field50" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field51" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field52" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field53" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field54" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field55" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field56" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field57" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field58" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field59" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field60" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field61" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field62" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field63" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field64" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field65" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field66" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field67" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field68" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field69" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field70" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field71" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field72" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field73" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field74" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field75" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field76" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field77" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field78" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field79" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field80" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field81" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field82" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field83" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field84" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field85" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field86" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field87" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field88" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field89" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field90" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field91" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field92" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field93" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field94" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field95" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field96" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field97" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field98" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field99" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="field100" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="list1" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="list2" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="testOtherObject1" type="{https://www.praca_magister/soap_vs_rest/test.com}TestOtherObject1"/>
 *         &lt;element name="testOtherObject2" type="{https://www.praca_magister/soap_vs_rest/test.com}TestOtherObject2"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "field1",
    "field2",
    "field3",
    "field4",
    "field5",
    "field6",
    "field7",
    "field8",
    "field9",
    "field10",
    "field11",
    "field12",
    "field13",
    "field14",
    "field15",
    "field16",
    "field17",
    "field18",
    "field19",
    "field20",
    "field21",
    "field22",
    "field23",
    "field24",
    "field25",
    "field26",
    "field27",
    "field28",
    "field29",
    "field30",
    "field31",
    "field32",
    "field33",
    "field34",
    "field35",
    "field36",
    "field37",
    "field38",
    "field39",
    "field40",
    "field41",
    "field42",
    "field43",
    "field44",
    "field45",
    "field46",
    "field47",
    "field48",
    "field49",
    "field50",
    "field51",
    "field52",
    "field53",
    "field54",
    "field55",
    "field56",
    "field57",
    "field58",
    "field59",
    "field60",
    "field61",
    "field62",
    "field63",
    "field64",
    "field65",
    "field66",
    "field67",
    "field68",
    "field69",
    "field70",
    "field71",
    "field72",
    "field73",
    "field74",
    "field75",
    "field76",
    "field77",
    "field78",
    "field79",
    "field80",
    "field81",
    "field82",
    "field83",
    "field84",
    "field85",
    "field86",
    "field87",
    "field88",
    "field89",
    "field90",
    "field91",
    "field92",
    "field93",
    "field94",
    "field95",
    "field96",
    "field97",
    "field98",
    "field99",
    "field100",
    "list1",
    "list2",
    "testOtherObject1",
    "testOtherObject2"
})
@XmlRootElement(name = "TestRequest", namespace = "https://www.praca_magister/soap_vs_rest/test.com")
public class TestRequest {

    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field1;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field2;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field3;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field4;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field5;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field6;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field7;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field8;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field9;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field10;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field11;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field12;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field13;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field14;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field15;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field16;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field17;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field18;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field19;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field20;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field21;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field22;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field23;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field24;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field25;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field26;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field27;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field28;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field29;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field30;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field31;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field32;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field33;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field34;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field35;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field36;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field37;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field38;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field39;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field40;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field41;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field42;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field43;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field44;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field45;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field46;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field47;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field48;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field49;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field50;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field51;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field52;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field53;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field54;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field55;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field56;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field57;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field58;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field59;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field60;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field61;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field62;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field63;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field64;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field65;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field66;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field67;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field68;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field69;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field70;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field71;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field72;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field73;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field74;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field75;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field76;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field77;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field78;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field79;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field80;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field81;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field82;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field83;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field84;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field85;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field86;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field87;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field88;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field89;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field90;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field91;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field92;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field93;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field94;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field95;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field96;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field97;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field98;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field99;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected String field100;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com")
    protected List<String> list1;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com")
    protected List<String> list2;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected TestOtherObject1 testOtherObject1;
    @XmlElement(namespace = "https://www.praca_magister/soap_vs_rest/test.com", required = true)
    protected TestOtherObject2 testOtherObject2;

    /**
     * Gets the value of the field1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField1() {
        return field1;
    }

    /**
     * Sets the value of the field1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField1(String value) {
        this.field1 = value;
    }

    /**
     * Gets the value of the field2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField2() {
        return field2;
    }

    /**
     * Sets the value of the field2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField2(String value) {
        this.field2 = value;
    }

    /**
     * Gets the value of the field3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField3() {
        return field3;
    }

    /**
     * Sets the value of the field3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField3(String value) {
        this.field3 = value;
    }

    /**
     * Gets the value of the field4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField4() {
        return field4;
    }

    /**
     * Sets the value of the field4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField4(String value) {
        this.field4 = value;
    }

    /**
     * Gets the value of the field5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField5() {
        return field5;
    }

    /**
     * Sets the value of the field5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField5(String value) {
        this.field5 = value;
    }

    /**
     * Gets the value of the field6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField6() {
        return field6;
    }

    /**
     * Sets the value of the field6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField6(String value) {
        this.field6 = value;
    }

    /**
     * Gets the value of the field7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField7() {
        return field7;
    }

    /**
     * Sets the value of the field7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField7(String value) {
        this.field7 = value;
    }

    /**
     * Gets the value of the field8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField8() {
        return field8;
    }

    /**
     * Sets the value of the field8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField8(String value) {
        this.field8 = value;
    }

    /**
     * Gets the value of the field9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField9() {
        return field9;
    }

    /**
     * Sets the value of the field9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField9(String value) {
        this.field9 = value;
    }

    /**
     * Gets the value of the field10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField10() {
        return field10;
    }

    /**
     * Sets the value of the field10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField10(String value) {
        this.field10 = value;
    }

    /**
     * Gets the value of the field11 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField11() {
        return field11;
    }

    /**
     * Sets the value of the field11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField11(String value) {
        this.field11 = value;
    }

    /**
     * Gets the value of the field12 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField12() {
        return field12;
    }

    /**
     * Sets the value of the field12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField12(String value) {
        this.field12 = value;
    }

    /**
     * Gets the value of the field13 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField13() {
        return field13;
    }

    /**
     * Sets the value of the field13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField13(String value) {
        this.field13 = value;
    }

    /**
     * Gets the value of the field14 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField14() {
        return field14;
    }

    /**
     * Sets the value of the field14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField14(String value) {
        this.field14 = value;
    }

    /**
     * Gets the value of the field15 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField15() {
        return field15;
    }

    /**
     * Sets the value of the field15 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField15(String value) {
        this.field15 = value;
    }

    /**
     * Gets the value of the field16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField16() {
        return field16;
    }

    /**
     * Sets the value of the field16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField16(String value) {
        this.field16 = value;
    }

    /**
     * Gets the value of the field17 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField17() {
        return field17;
    }

    /**
     * Sets the value of the field17 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField17(String value) {
        this.field17 = value;
    }

    /**
     * Gets the value of the field18 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField18() {
        return field18;
    }

    /**
     * Sets the value of the field18 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField18(String value) {
        this.field18 = value;
    }

    /**
     * Gets the value of the field19 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField19() {
        return field19;
    }

    /**
     * Sets the value of the field19 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField19(String value) {
        this.field19 = value;
    }

    /**
     * Gets the value of the field20 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField20() {
        return field20;
    }

    /**
     * Sets the value of the field20 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField20(String value) {
        this.field20 = value;
    }

    /**
     * Gets the value of the field21 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField21() {
        return field21;
    }

    /**
     * Sets the value of the field21 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField21(String value) {
        this.field21 = value;
    }

    /**
     * Gets the value of the field22 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField22() {
        return field22;
    }

    /**
     * Sets the value of the field22 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField22(String value) {
        this.field22 = value;
    }

    /**
     * Gets the value of the field23 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField23() {
        return field23;
    }

    /**
     * Sets the value of the field23 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField23(String value) {
        this.field23 = value;
    }

    /**
     * Gets the value of the field24 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField24() {
        return field24;
    }

    /**
     * Sets the value of the field24 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField24(String value) {
        this.field24 = value;
    }

    /**
     * Gets the value of the field25 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField25() {
        return field25;
    }

    /**
     * Sets the value of the field25 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField25(String value) {
        this.field25 = value;
    }

    /**
     * Gets the value of the field26 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField26() {
        return field26;
    }

    /**
     * Sets the value of the field26 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField26(String value) {
        this.field26 = value;
    }

    /**
     * Gets the value of the field27 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField27() {
        return field27;
    }

    /**
     * Sets the value of the field27 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField27(String value) {
        this.field27 = value;
    }

    /**
     * Gets the value of the field28 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField28() {
        return field28;
    }

    /**
     * Sets the value of the field28 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField28(String value) {
        this.field28 = value;
    }

    /**
     * Gets the value of the field29 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField29() {
        return field29;
    }

    /**
     * Sets the value of the field29 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField29(String value) {
        this.field29 = value;
    }

    /**
     * Gets the value of the field30 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField30() {
        return field30;
    }

    /**
     * Sets the value of the field30 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField30(String value) {
        this.field30 = value;
    }

    /**
     * Gets the value of the field31 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField31() {
        return field31;
    }

    /**
     * Sets the value of the field31 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField31(String value) {
        this.field31 = value;
    }

    /**
     * Gets the value of the field32 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField32() {
        return field32;
    }

    /**
     * Sets the value of the field32 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField32(String value) {
        this.field32 = value;
    }

    /**
     * Gets the value of the field33 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField33() {
        return field33;
    }

    /**
     * Sets the value of the field33 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField33(String value) {
        this.field33 = value;
    }

    /**
     * Gets the value of the field34 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField34() {
        return field34;
    }

    /**
     * Sets the value of the field34 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField34(String value) {
        this.field34 = value;
    }

    /**
     * Gets the value of the field35 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField35() {
        return field35;
    }

    /**
     * Sets the value of the field35 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField35(String value) {
        this.field35 = value;
    }

    /**
     * Gets the value of the field36 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField36() {
        return field36;
    }

    /**
     * Sets the value of the field36 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField36(String value) {
        this.field36 = value;
    }

    /**
     * Gets the value of the field37 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField37() {
        return field37;
    }

    /**
     * Sets the value of the field37 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField37(String value) {
        this.field37 = value;
    }

    /**
     * Gets the value of the field38 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField38() {
        return field38;
    }

    /**
     * Sets the value of the field38 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField38(String value) {
        this.field38 = value;
    }

    /**
     * Gets the value of the field39 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField39() {
        return field39;
    }

    /**
     * Sets the value of the field39 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField39(String value) {
        this.field39 = value;
    }

    /**
     * Gets the value of the field40 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField40() {
        return field40;
    }

    /**
     * Sets the value of the field40 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField40(String value) {
        this.field40 = value;
    }

    /**
     * Gets the value of the field41 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField41() {
        return field41;
    }

    /**
     * Sets the value of the field41 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField41(String value) {
        this.field41 = value;
    }

    /**
     * Gets the value of the field42 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField42() {
        return field42;
    }

    /**
     * Sets the value of the field42 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField42(String value) {
        this.field42 = value;
    }

    /**
     * Gets the value of the field43 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField43() {
        return field43;
    }

    /**
     * Sets the value of the field43 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField43(String value) {
        this.field43 = value;
    }

    /**
     * Gets the value of the field44 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField44() {
        return field44;
    }

    /**
     * Sets the value of the field44 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField44(String value) {
        this.field44 = value;
    }

    /**
     * Gets the value of the field45 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField45() {
        return field45;
    }

    /**
     * Sets the value of the field45 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField45(String value) {
        this.field45 = value;
    }

    /**
     * Gets the value of the field46 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField46() {
        return field46;
    }

    /**
     * Sets the value of the field46 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField46(String value) {
        this.field46 = value;
    }

    /**
     * Gets the value of the field47 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField47() {
        return field47;
    }

    /**
     * Sets the value of the field47 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField47(String value) {
        this.field47 = value;
    }

    /**
     * Gets the value of the field48 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField48() {
        return field48;
    }

    /**
     * Sets the value of the field48 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField48(String value) {
        this.field48 = value;
    }

    /**
     * Gets the value of the field49 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField49() {
        return field49;
    }

    /**
     * Sets the value of the field49 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField49(String value) {
        this.field49 = value;
    }

    /**
     * Gets the value of the field50 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField50() {
        return field50;
    }

    /**
     * Sets the value of the field50 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField50(String value) {
        this.field50 = value;
    }

    /**
     * Gets the value of the field51 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField51() {
        return field51;
    }

    /**
     * Sets the value of the field51 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField51(String value) {
        this.field51 = value;
    }

    /**
     * Gets the value of the field52 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField52() {
        return field52;
    }

    /**
     * Sets the value of the field52 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField52(String value) {
        this.field52 = value;
    }

    /**
     * Gets the value of the field53 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField53() {
        return field53;
    }

    /**
     * Sets the value of the field53 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField53(String value) {
        this.field53 = value;
    }

    /**
     * Gets the value of the field54 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField54() {
        return field54;
    }

    /**
     * Sets the value of the field54 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField54(String value) {
        this.field54 = value;
    }

    /**
     * Gets the value of the field55 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField55() {
        return field55;
    }

    /**
     * Sets the value of the field55 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField55(String value) {
        this.field55 = value;
    }

    /**
     * Gets the value of the field56 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField56() {
        return field56;
    }

    /**
     * Sets the value of the field56 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField56(String value) {
        this.field56 = value;
    }

    /**
     * Gets the value of the field57 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField57() {
        return field57;
    }

    /**
     * Sets the value of the field57 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField57(String value) {
        this.field57 = value;
    }

    /**
     * Gets the value of the field58 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField58() {
        return field58;
    }

    /**
     * Sets the value of the field58 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField58(String value) {
        this.field58 = value;
    }

    /**
     * Gets the value of the field59 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField59() {
        return field59;
    }

    /**
     * Sets the value of the field59 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField59(String value) {
        this.field59 = value;
    }

    /**
     * Gets the value of the field60 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField60() {
        return field60;
    }

    /**
     * Sets the value of the field60 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField60(String value) {
        this.field60 = value;
    }

    /**
     * Gets the value of the field61 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField61() {
        return field61;
    }

    /**
     * Sets the value of the field61 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField61(String value) {
        this.field61 = value;
    }

    /**
     * Gets the value of the field62 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField62() {
        return field62;
    }

    /**
     * Sets the value of the field62 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField62(String value) {
        this.field62 = value;
    }

    /**
     * Gets the value of the field63 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField63() {
        return field63;
    }

    /**
     * Sets the value of the field63 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField63(String value) {
        this.field63 = value;
    }

    /**
     * Gets the value of the field64 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField64() {
        return field64;
    }

    /**
     * Sets the value of the field64 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField64(String value) {
        this.field64 = value;
    }

    /**
     * Gets the value of the field65 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField65() {
        return field65;
    }

    /**
     * Sets the value of the field65 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField65(String value) {
        this.field65 = value;
    }

    /**
     * Gets the value of the field66 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField66() {
        return field66;
    }

    /**
     * Sets the value of the field66 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField66(String value) {
        this.field66 = value;
    }

    /**
     * Gets the value of the field67 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField67() {
        return field67;
    }

    /**
     * Sets the value of the field67 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField67(String value) {
        this.field67 = value;
    }

    /**
     * Gets the value of the field68 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField68() {
        return field68;
    }

    /**
     * Sets the value of the field68 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField68(String value) {
        this.field68 = value;
    }

    /**
     * Gets the value of the field69 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField69() {
        return field69;
    }

    /**
     * Sets the value of the field69 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField69(String value) {
        this.field69 = value;
    }

    /**
     * Gets the value of the field70 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField70() {
        return field70;
    }

    /**
     * Sets the value of the field70 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField70(String value) {
        this.field70 = value;
    }

    /**
     * Gets the value of the field71 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField71() {
        return field71;
    }

    /**
     * Sets the value of the field71 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField71(String value) {
        this.field71 = value;
    }

    /**
     * Gets the value of the field72 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField72() {
        return field72;
    }

    /**
     * Sets the value of the field72 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField72(String value) {
        this.field72 = value;
    }

    /**
     * Gets the value of the field73 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField73() {
        return field73;
    }

    /**
     * Sets the value of the field73 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField73(String value) {
        this.field73 = value;
    }

    /**
     * Gets the value of the field74 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField74() {
        return field74;
    }

    /**
     * Sets the value of the field74 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField74(String value) {
        this.field74 = value;
    }

    /**
     * Gets the value of the field75 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField75() {
        return field75;
    }

    /**
     * Sets the value of the field75 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField75(String value) {
        this.field75 = value;
    }

    /**
     * Gets the value of the field76 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField76() {
        return field76;
    }

    /**
     * Sets the value of the field76 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField76(String value) {
        this.field76 = value;
    }

    /**
     * Gets the value of the field77 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField77() {
        return field77;
    }

    /**
     * Sets the value of the field77 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField77(String value) {
        this.field77 = value;
    }

    /**
     * Gets the value of the field78 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField78() {
        return field78;
    }

    /**
     * Sets the value of the field78 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField78(String value) {
        this.field78 = value;
    }

    /**
     * Gets the value of the field79 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField79() {
        return field79;
    }

    /**
     * Sets the value of the field79 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField79(String value) {
        this.field79 = value;
    }

    /**
     * Gets the value of the field80 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField80() {
        return field80;
    }

    /**
     * Sets the value of the field80 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField80(String value) {
        this.field80 = value;
    }

    /**
     * Gets the value of the field81 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField81() {
        return field81;
    }

    /**
     * Sets the value of the field81 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField81(String value) {
        this.field81 = value;
    }

    /**
     * Gets the value of the field82 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField82() {
        return field82;
    }

    /**
     * Sets the value of the field82 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField82(String value) {
        this.field82 = value;
    }

    /**
     * Gets the value of the field83 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField83() {
        return field83;
    }

    /**
     * Sets the value of the field83 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField83(String value) {
        this.field83 = value;
    }

    /**
     * Gets the value of the field84 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField84() {
        return field84;
    }

    /**
     * Sets the value of the field84 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField84(String value) {
        this.field84 = value;
    }

    /**
     * Gets the value of the field85 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField85() {
        return field85;
    }

    /**
     * Sets the value of the field85 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField85(String value) {
        this.field85 = value;
    }

    /**
     * Gets the value of the field86 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField86() {
        return field86;
    }

    /**
     * Sets the value of the field86 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField86(String value) {
        this.field86 = value;
    }

    /**
     * Gets the value of the field87 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField87() {
        return field87;
    }

    /**
     * Sets the value of the field87 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField87(String value) {
        this.field87 = value;
    }

    /**
     * Gets the value of the field88 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField88() {
        return field88;
    }

    /**
     * Sets the value of the field88 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField88(String value) {
        this.field88 = value;
    }

    /**
     * Gets the value of the field89 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField89() {
        return field89;
    }

    /**
     * Sets the value of the field89 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField89(String value) {
        this.field89 = value;
    }

    /**
     * Gets the value of the field90 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField90() {
        return field90;
    }

    /**
     * Sets the value of the field90 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField90(String value) {
        this.field90 = value;
    }

    /**
     * Gets the value of the field91 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField91() {
        return field91;
    }

    /**
     * Sets the value of the field91 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField91(String value) {
        this.field91 = value;
    }

    /**
     * Gets the value of the field92 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField92() {
        return field92;
    }

    /**
     * Sets the value of the field92 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField92(String value) {
        this.field92 = value;
    }

    /**
     * Gets the value of the field93 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField93() {
        return field93;
    }

    /**
     * Sets the value of the field93 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField93(String value) {
        this.field93 = value;
    }

    /**
     * Gets the value of the field94 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField94() {
        return field94;
    }

    /**
     * Sets the value of the field94 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField94(String value) {
        this.field94 = value;
    }

    /**
     * Gets the value of the field95 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField95() {
        return field95;
    }

    /**
     * Sets the value of the field95 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField95(String value) {
        this.field95 = value;
    }

    /**
     * Gets the value of the field96 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField96() {
        return field96;
    }

    /**
     * Sets the value of the field96 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField96(String value) {
        this.field96 = value;
    }

    /**
     * Gets the value of the field97 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField97() {
        return field97;
    }

    /**
     * Sets the value of the field97 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField97(String value) {
        this.field97 = value;
    }

    /**
     * Gets the value of the field98 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField98() {
        return field98;
    }

    /**
     * Sets the value of the field98 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField98(String value) {
        this.field98 = value;
    }

    /**
     * Gets the value of the field99 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField99() {
        return field99;
    }

    /**
     * Sets the value of the field99 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField99(String value) {
        this.field99 = value;
    }

    /**
     * Gets the value of the field100 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField100() {
        return field100;
    }

    /**
     * Sets the value of the field100 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField100(String value) {
        this.field100 = value;
    }

    /**
     * Gets the value of the list1 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the list1 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getList1().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getList1() {
        if (list1 == null) {
            list1 = new ArrayList<String>();
        }
        return this.list1;
    }

    /**
     * Gets the value of the list2 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the list2 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getList2().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getList2() {
        if (list2 == null) {
            list2 = new ArrayList<String>();
        }
        return this.list2;
    }

    /**
     * Gets the value of the testOtherObject1 property.
     * 
     * @return
     *     possible object is
     *     {@link TestOtherObject1 }
     *     
     */
    public TestOtherObject1 getTestOtherObject1() {
        return testOtherObject1;
    }

    /**
     * Sets the value of the testOtherObject1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestOtherObject1 }
     *     
     */
    public void setTestOtherObject1(TestOtherObject1 value) {
        this.testOtherObject1 = value;
    }

    /**
     * Gets the value of the testOtherObject2 property.
     * 
     * @return
     *     possible object is
     *     {@link TestOtherObject2 }
     *     
     */
    public TestOtherObject2 getTestOtherObject2() {
        return testOtherObject2;
    }

    /**
     * Sets the value of the testOtherObject2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestOtherObject2 }
     *     
     */
    public void setTestOtherObject2(TestOtherObject2 value) {
        this.testOtherObject2 = value;
    }

}
