//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.23 at 05:40:49 PM CET 
//


package soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestOtherObject1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestOtherObject1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="testField1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="testField2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="testField3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="list" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestOtherObject1", namespace = "https://www.praca_magister/soap_vs_rest/test.com", propOrder = {
    "testField1",
    "testField2",
    "testField3",
    "list"
})
public class TestOtherObject1 {

    @XmlElement(required = true)
    protected String testField1;
    @XmlElement(required = true)
    protected String testField2;
    @XmlElement(required = true)
    protected String testField3;
    protected List<String> list;

    /**
     * Gets the value of the testField1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestField1() {
        return testField1;
    }

    /**
     * Sets the value of the testField1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestField1(String value) {
        this.testField1 = value;
    }

    /**
     * Gets the value of the testField2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestField2() {
        return testField2;
    }

    /**
     * Sets the value of the testField2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestField2(String value) {
        this.testField2 = value;
    }

    /**
     * Gets the value of the testField3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestField3() {
        return testField3;
    }

    /**
     * Sets the value of the testField3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestField3(String value) {
        this.testField3 = value;
    }

    /**
     * Gets the value of the list property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the list property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getList() {
        if (list == null) {
            list = new ArrayList<String>();
        }
        return this.list;
    }

}
